language: go

go:
  - 1.12.x

env:
  global: 
    - GO111MODULE=on

services:
  - mysql
  - postgres

before_install:
  - mysql -e "CREATE DATABASE miga;"
  - mysql -e "CREATE USER user@localhost IDENTIFIED BY 'password'";
  - mysql -e "GRANT ALL ON miga.* TO user@localhost";
  - psql -U postgres -c 'CREATE DATABASE miga;'
  - psql -U postgres -c "CREATE USER \"user\" WITH PASSWORD 'password'";

install:
  - make build

script:
  - make test
