language: go

go:
  - 1.15.x

env:
  global: 
    - GO111MODULE=on

services:
  - mysql
  - postgresql

before_install:
  - docker run --rm=true -p 9000:9000 --name miga-clickhouse -e CLICKHOUSE_DB=miga -e CLICKHOUSE_USER=user -e CLICKHOUSE_PASSWORD=password -d yandex/clickhouse-server
  - mysql -e "CREATE DATABASE miga;"
  - mysql -e "CREATE USER user@localhost IDENTIFIED BY 'password'";
  - mysql -e "GRANT ALL ON miga.* TO user@localhost";
  - psql -U postgres -c 'CREATE DATABASE miga;'
  - psql -U postgres -c "CREATE USER \"user\" WITH PASSWORD 'password'";

install:
  - make build

script:
  - make test
